import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * MakersFlow shared Supabase client.
 *
 * This web app connects to the SAME Supabase project used by the
 * MakersFlow mobile app (React Native + Expo). We intentionally do not
 * use Lovable Cloud's auto-provisioned project here — credentials are
 * provided via environment variables so both apps share auth, RLS,
 * and data.
 *
 * Required env (publishable / anon key only — never the service role):
 *   VITE_SUPABASE_URL
 *   VITE_SUPABASE_PUBLISHABLE_KEY  (or VITE_SUPABASE_ANON_KEY)
 */

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ??
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Surface a clear error early in dev rather than a confusing auth failure later.

  console.warn(
    "[makersflow] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. " +
      "Set them to the existing MakersFlow Supabase project credentials.",
  );
}

// NOTE on typing: this project uses a hand-maintained `Database` type rather
// than one generated by `supabase gen types`. With @supabase/supabase-js v2.108+
// the stricter generic inference collapses query results to `never` when the
// hand-written shape isn't byte-identical to what the generator would emit.
// To keep end-to-end usability without fighting the generator, we type the
// exported client as `SupabaseClient<Database, "public", any>`. Row shapes are
// still applied explicitly where it matters (callers cast `.select()` results
// to the Row types in lib/*-data.ts), and writes accept partial payloads.
export const supabase: SupabaseClient<Database, "public", any> = createClient<
  Database,
  "public",
  any
>(
  SUPABASE_URL ?? "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY ?? "placeholder-anon-key",
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: "makersflow.auth",
    },
  },
);

export type { SupabaseClient };
export type { Database };
